/*
 * This Scala Testsuite was generated by the Gradle 'init' task.
 */
package com.codingmaniacs.scala.akka

import org.specs2.mutable.Specification

class LibrarySpec extends Specification {
  "SomeLibraryMethod" should {
    "always be true" in {
      val library = new Library()
      val result = library.someLibraryMethod()
      result must beTrue
    }
  }
}
